name: Build and Push Server Docker Image

# Trigger the workflow on pushes to the 'main' branch and when changes are made in 'server/server'
on:
  push:
    paths:
      - "server/server/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 23
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: "temurin"

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0


      # Build the Java project using Gradle
      - name: Build with Gradle
        working-directory: server/server
        run: gradlew clean bootjar

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        working-directory: server/server
        run: |
          docker build -t ghart10/pidrive-server:latest .

      # Push the Docker image to the registry
      - name: Push Docker image
        run: |
          docker push ghart10/pidrive-server:latest
